name: zento

services:
  nginx:
    image: 'nginx:alpine'
    restart: unless-stopped
    ports:
      - '8081:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./backend:/var/www/laravel:z
    depends_on:
      - php
      - mysql

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/laravel:z
    user: "${UID:-1000}:${GID:-1000}"

  mysql:
    image: 'mysql:8.0'
    restart: unless-stopped
    ports:
      - '3316:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-visapath}
      MYSQL_USER: ${DB_USERNAME:-visapath}
      MYSQL_PASSWORD: ${DB_PASSWORD:-visapath}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-visapath}
    volumes:
      - mysql_data:/var/lib/mysql

  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.Dockerfile
    profiles:
      - tools
    volumes:
      - ./backend:/var/www/laravel:z
    user: "${UID:-1000}:${GID:-1000}"

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    profiles:
      - tools
    volumes:
      - ./backend:/var/www/laravel:z
    user: "${UID:-1000}:${GID:-1000}"

  node:
    image: 'node:22-alpine'
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_PROXY_TARGET=http://nginx
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  mysql_data:
  node_modules:
